title: Julian Wilson # your name (or website title) here
logo: "images/headshot.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="http://www.linkedin.com/in/julianwilson24">LinkedIn</a> 
  <br>
  <a href="https://docs.google.com/document/d/11CHrooa376Wcva-UGta5efxMT89781AWcsnLajJ2IQI/edit?usp=sharing">Resume</a>  
  <br>
  <a " class="btn btn--info">Portfolio</a>  
  <br>
  <a href="https://www.GitHub.com/Juwilson24/">GitHub</a>  
  
theme: jekyll-theme-minimal
